In [2]:
import numpy as np

In [3]:
# ESCALAR
x = np.array(6)
print ("x: ", x)
print ("x ndim: ", x.ndim) # numero de dimensoes
print ("x shape:", x.shape) # estrutura
print ("x size: ", x.size) # numero total de elementos
print ("x dtype: ", x.dtype) # tipo dos dados

x:  6
x ndim:  0
x shape: ()
x size:  1
x dtype:  int64


In [4]:
# VETOR
x = np.array([1.3 , 2.2 , 1.7])
print ("x: ", x)
print ("x ndim: ", x.ndim) # numero de dimensoes
print ("x shape:", x.shape) # estrutura
print ("x size: ", x.size) # numero total de elementos
print ("x dtype: ", x.dtype) # tipo dos dados, note o float

x:  [1.3 2.2 1.7]
x ndim:  1
x shape: (3,)
x size:  3
x dtype:  float64


In [5]:
# MATRIZ
x = np.array([[1,2], [3,4]])
print ("x:\n", x)
print ("x ndim: ", x.ndim)
print ("x shape:", x.shape)
print ("x size: ", x.size)
print ("x dtype: ", x.dtype)

x:
 [[1 2]
 [3 4]]
x ndim:  2
x shape: (2, 2)
x size:  4
x dtype:  int64


In [6]:
# TENSOR
x = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print ("x:\n", x)
print ("x ndim: ", x.ndim)
print ("x shape:", x.shape)
print ("x size: ", x.size)
print ("x dtype: ", x.dtype)

x:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
x ndim:  3
x shape: (2, 2, 2)
x size:  8
x dtype:  int64


In [8]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Elemento especifico
print(arr[0, 0])    # 1

# Linha inteira
print(arr[0])       # [1 2 3]

# Fatiamento
print(arr[0:2, 1:]) # [[2 3]
                    #  [5 6]]

# Indexacaoo booleana
print(arr > 5)      # [[False False False]
                    #  [False False True]
                    #  [True True True]]
print(arr[arr > 5]) # [6 7 8 9]

1
[1 2 3]
[[2 3]
 [5 6]]
[[False False False]
 [False False  True]
 [ True  True  True]]
[6 7 8 9]


In [9]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Funcoes universais (ufuncs)
print(np.sqrt(arr1))  # [1. 1.41421356 1.73205081]
print(np.exp(arr1))   # [2.71828183 7.3890561 20.08553692]
print(np.sin(arr1))   # [0.84147098 0.90929743 0.14112001]

# Operacoes aritmeticas

print(arr1 + arr2)  # ou np.add(arr1, arr2) -> [5 7 9]
print(arr1 * arr2)  # ou np.multiply(arr1, arr2) -> [4 10 18]
print(arr1 ** 2)    # [1 4 9]

a = np.arange(5) # array([0, 1, 2, 3, 4])
a + 1 # array([1, 2, 3, 4, 5])

[1.         1.41421356 1.73205081]
[ 2.71828183  7.3890561  20.08553692]
[0.84147098 0.90929743 0.14112001]
[5 7 9]
[ 4 10 18]
[1 4 9]


array([1, 2, 3, 4, 5])

In [10]:
a = np.array([[1,2,3], [4,5,6]], dtype=np.float64) # podemos especificar o dtype
b = np.array([[7,8], [9,10], [11, 12]], dtype=np.float64)
c = a.dot(b)
print (f"{a.shape} x {b.shape} = {c.shape}")
print (c)

(2, 3) x (3, 2) = (2, 2)
[[ 58.  64.]
 [139. 154.]]


In [11]:
a = np.array([[1, 2], [3, 4]])  
b = np.array([[5, 6]])          

c = a.dot(b.T)
print(c) 

c = a.dot(np.transpose(b)) # mesmo resultado que o valor anterior
print(c) 

[[17]
 [39]]
[[17]
 [39]]


In [12]:
a = np.array([[1, 2, 3], [4, 5, 6]]) 
b = np.array([7, 8, 9])              

c = a.dot(b.reshape(3, 1)) # b foi redimensionado para 3x1
print(c)

[[ 50]
 [122]]


In [13]:
x = np.array([[1,2],[3,4]])
print (x)
print ("sum all: ", np.sum(x)) # soma todos os elementos
print ("sum axis=0: ", np.sum(x, axis=0)) # soma ao longo das colunas
print ("sum axis=1: ", np.sum(x, axis=1)) # soma ao longo das linhas 

print("\n")

x = np.array([[1,2,3], [4,5,6]])
print ("min: ", x.min())
print ("max: ", x.max())
print("argmin: ", np.argmin(x)) # Indice do menor valor
print("argmax: ", np.argmax(x)) # Indice do maior valor
print("mean: ", np.mean(x)) # media
print ("min axis=0: ", x.min(axis=0))
print ("min axis=1: ", x.min(axis=1))

[[1 2]
 [3 4]]
sum all:  10
sum axis=0:  [4 6]
sum axis=1:  [3 7]


min:  1
max:  6
argmin:  0
argmax:  5
mean:  3.5
min axis=0:  [1 2 3]
min axis=1:  [1 4]


In [14]:
matriz = np.array([[1, 2, 3],
                   [4, 5, 6]])
vetor = np.array([10, 20, 30])

# O vetor e "transmitido" para cada linha da matriz
print(matriz + vetor)
# [[11 22 33]
#  [14 25 36]]

[[11 22 33]
 [14 25 36]]


In [15]:
arr = np.array([1, 2, 3, 4, 5, 6])

# Reshape (olha ele ai novamente)
print(arr.reshape(2, 3))
# [[1 2 3]
#  [4 5 6]]

# Transpose (olha ele ai novamente)
matriz = np.array([[1, 2], [3, 4]])
print(matriz.T) # ou np.transpose(matriz)
# [[1 3]
#  [2 4]]

# Flatten - transforma em vetor (1D)
print(matriz.flatten())  # [1 2 3 4]

[[1 2 3]
 [4 5 6]]
[[1 3]
 [2 4]]
[1 2 3 4]


In [16]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

# Concatenando ao longo do eixo 0 (linhas)
print(np.concatenate((a, b), axis=0))  
# [[1 2]
#  [3 4]
#  [5 6]]

# Concatenando ao longo do eixo 1 (colunas)
print(np.concatenate((a, b.T), axis=1))
# [[1 2 5]
#  [3 4 6]]

# Equivalentes diretos
print(np.hstack((a, b.T)))  # Horizontal, igual concatenate(axis=1)
print(np.vstack((a, b)))    # Vertical, igual concatenate(axis=0)

[[1 2]
 [3 4]
 [5 6]]
[[1 2 5]
 [3 4 6]]
[[1 2 5]
 [3 4 6]]
[[1 2]
 [3 4]
 [5 6]]
